"""Job submission/management MCP tools."""

from __future__ import annotations

import logging
import re
from typing import Any, Dict, List

from ..data_service import SageDataService
from ..job_service import SageJobService
from ..job_templates import JobTemplates
from ..models import (
    NodeID,
    PluginArguments,
    PluginSpec,
    SageJob,
    SelectorRequirements,
    TimeRange,
)
from ..utils import parse_time_range, safe_timestamp_format


logger = logging.getLogger(__name__)


# Job-name keywords → plugin regex patterns
_JOB_TO_PLUGIN_PATTERNS: Dict[str, List[str]] = {
    "audio": [".*audio.*", ".*sage-audio.*"],
    "air-quality": [".*air-quality.*", ".*airquality.*"],
    "cloud": [".*cloud.*"],
    "image": [".*image.*", ".*sampler.*"],
    "camera": [".*camera.*", ".*imagesampler.*"],
    "sound": [".*sound.*", ".*audio.*"],
    "weather": [".*weather.*", ".*wxt.*"],
    "rain": [".*rain.*", ".*raingauge.*"],
    "temperature": [".*temperature.*", ".*temp.*"],
    "motion": [".*motion.*"],
    "ptz": [".*ptz.*"],
    "yolo": [".*yolo.*"],
    "bird": [".*bird.*", ".*avian.*"],
    "mobotix": [".*mobotix.*"],
}


def register(
    mcp,
    *,
    data_service: SageDataService,
    job_service: SageJobService,
    find_plugins_for_task,
) -> None:
    @mcp.tool
    def submit_sage_job(
        job_name: str,
        nodes: str,
        plugin_image: str = "",
        plugin_args: str = "",
        science_rules: str = "",
        selector_requirements: str = "",
    ) -> str:
        """Submit a Sage job. If ``plugin_image`` is empty, returns recommendations."""
        try:
            if not plugin_image:
                rec = find_plugins_for_task(job_name)
                rec += "\n\nTIP: For easier job submission, try:\n"
                rec += "• submit_plugin_job(plugin_type, job_name, nodes)\n"
                rec += "• submit_multi_plugin_job(job_name, nodes, plugins_config)\n"
                return rec

            node_list = [n.strip() for n in nodes.split(",") if n.strip()]
            if not node_list:
                raise ValueError("No valid nodes specified")

            plugin = PluginSpec(
                name=job_name,
                image=plugin_image,
                args=PluginArguments.from_string(plugin_args),
                selector=SelectorRequirements.from_json_str(selector_requirements),
            )
            job = SageJob(
                name=job_name,
                nodes=node_list,
                plugins=[plugin],
                science_rules=[r.strip() for r in science_rules.split(",") if r.strip()],
            )
            success, result = job_service.submit_job(job)
            return result if success else f"Failed to submit job: {result}"
        except Exception as e:
            logger.error(f"Error submitting job: {e}")
            return f"Error submitting job: {e}"

    @mcp.tool
    def check_job_status(job_id: str) -> str:
        """Check the status of a submitted Sage job."""
        return job_service.check_job_status(job_id)

    @mcp.tool
    def query_job_data(
        job_name: str, node_id: str = "", time_range: str = "-30m", data_type: str = "upload"
    ) -> str:
        """Query data generated by a running Sage job."""
        try:
            validated_time = TimeRange(value=time_range)
            validated_node = NodeID(value=node_id) if node_id else None

            plugin_patterns: List[str] = []
            if not job_name.startswith(".*"):
                plugin_patterns.append(f".*{job_name}.*")
            for keyword, patterns in _JOB_TO_PLUGIN_PATTERNS.items():
                if keyword in job_name.lower():
                    plugin_patterns.extend(patterns)

            filter_params: Dict[str, Any] = {}
            if plugin_patterns:
                seen = []
                for p in plugin_patterns:
                    if p not in seen:
                        seen.append(p)
                filter_params["plugin"] = "|".join(seen)
            else:
                filter_params["plugin"] = (
                    job_name if job_name.startswith(".*") else f".*{job_name}.*"
                )

            if validated_node:
                filter_params["vsn"] = str(validated_node)
            if data_type != "upload":
                filter_params["name"] = data_type

            start, end = parse_time_range(validated_time)
            df = data_service.query_data(start, end, filter_params)

            if df.empty:
                words = re.findall(r"\w+", job_name.lower())
                broader = [f".*{w}.*" for w in words if len(w) > 2]
                if broader:
                    filter_params["plugin"] = "|".join(broader)
                    df = data_service.query_data(start, end, filter_params)

            if df.empty:
                return (
                    f"No data found for job '{job_name}' in the last {validated_time}. "
                    "The job may still be starting or not producing data yet."
                )

            lines = [f"Job Data Summary for '{job_name}' (last {validated_time}):\n"]
            lines.append(f"Total records: {len(df)}")
            lines.append(f"Nodes reporting: {df['meta.vsn'].nunique() if 'meta.vsn' in df.columns else 0}")
            lines.append(f"Plugins active: {df['plugin'].nunique() if 'plugin' in df.columns else 0}")
            lines.append(f"Measurement types: {df['name'].nunique() if 'name' in df.columns else 0}")
            if "plugin" in df.columns:
                lines.append(f"\nPlugins: {', '.join(sorted(df['plugin'].unique()))}")
            if "name" in df.columns:
                lines.append(f"Measurements: {', '.join(sorted(df['name'].unique()))}")
            if "timestamp" in df.columns:
                lines.append(
                    f"\nTime range: {safe_timestamp_format(df['timestamp'].min())} "
                    f"to {safe_timestamp_format(df['timestamp'].max())}"
                )
            lines.append("\nRecent data sample:")
            for _, row in df.sort_values("timestamp", ascending=False).head(5).iterrows():
                value = row.get("value", "N/A")
                sample = (
                    f"  {safe_timestamp_format(row.get('timestamp', 'N/A'))} | "
                    f"Node {row.get('meta.vsn', 'N/A')} | {row.get('name', 'N/A')}"
                )
                if isinstance(value, (int, float)):
                    sample += f" | Value: {value:.2f}"
                elif value != "N/A":
                    sample += f" | Value: {value}"
                sample += f" | Plugin: {row.get('plugin', 'N/A')}"
                lines.append(sample)
            return "\n".join(lines)
        except Exception as e:
            logger.error(f"Error querying job data: {e}")
            return f"Error querying job data: {e}"

    @mcp.tool
    def force_remove_job(job_id: str) -> str:
        """Force remove a job from the scheduler."""
        return job_service.force_remove_job(job_id)

    @mcp.tool
    def suspend_job(job_id: str) -> str:
        """Suspend a job in the scheduler."""
        return job_service.suspend_job(job_id)

    @mcp.tool
    def submit_plugin_job(plugin_type: str, job_name: str, nodes: str) -> str:
        """Submit a pre-configured plugin job.

        Supported plugin types: air_quality, audio_sampler, camera_sampler,
        camera_sampler_top.
        """
        try:
            node_list = [NodeID(value=n.strip()).value for n in nodes.split(",") if n.strip()]
            if not node_list:
                return "Error: No valid nodes specified"

            if plugin_type == "air_quality":
                job = JobTemplates.air_quality(job_name=job_name, nodes=node_list)
            elif plugin_type == "audio_sampler":
                job = JobTemplates.audio_sampler(job_name=job_name, nodes=node_list)
            elif plugin_type == "camera_sampler":
                job = JobTemplates.camera_sampler(job_name=job_name, nodes=node_list, camera_position="bottom")
            elif plugin_type == "camera_sampler_top":
                job = JobTemplates.camera_sampler(job_name=job_name, nodes=node_list, camera_position="top")
            else:
                return (
                    f"Error: Unknown plugin type '{plugin_type}'. Available: "
                    "air_quality, audio_sampler, camera_sampler, camera_sampler_top"
                )
            _, message = job_service.submit_job(job)
            return message
        except Exception as e:
            logger.error(f"Error submitting {plugin_type} job: {e}")
            return f"Error submitting {plugin_type} job: {e}"

    @mcp.tool
    def submit_multi_plugin_job(job_name: str, nodes: str, plugins_config: str) -> str:
        """Submit a multi-plugin job — currently only the pre-configured ML suite preset."""
        import json

        try:
            node_list = [n.strip() for n in nodes.split(",") if n.strip()]
            if not node_list:
                return "Error: No valid nodes specified"
            try:
                config = json.loads(plugins_config) if plugins_config else {}
            except json.JSONDecodeError as e:
                return f"Error: Invalid JSON in plugins_config: {e}"

            if isinstance(config, dict) and config.get("preset") == "ml_suite":
                job = JobTemplates.multi_plugin_ml_suite(
                    job_name=job_name,
                    nodes=node_list,
                    cloud_cover_interval=int(config.get("cloud_cover_interval", 10)),
                    sound_event_interval=int(config.get("sound_event_interval", 10)),
                    avian_monitoring_interval=int(config.get("avian_monitoring_interval", 5)),
                    cloud_motion_interval=int(config.get("cloud_motion_interval", 20)),
                )
                _, message = job_service.submit_job(job)
                return message
            return (
                "Error: Only the 'ml_suite' preset is supported for multi-plugin jobs "
                "at the moment. Pass plugins_config='{\"preset\": \"ml_suite\"}' or use "
                "submit_plugin_job() for individual plugins."
            )
        except Exception as e:
            logger.error(f"Error submitting multi-plugin job: {e}")
            return f"Error submitting multi-plugin job: {e}"
